export const OVERFLOW_URLS = [
    "https://services2.arcgis.com/g6o32ZDQ33GpCIu3/arcgis/rest/services/Thames_Water_Storm_Overflow_Activity_(Production)_view/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services5.arcgis.com/5eoLvR0f8HKb7HWP/arcgis/rest/services/United_Utilities_Storm_Overflow_Activity/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services-eu1.arcgis.com/1WqkK5cDKUbF0CkH/arcgis/rest/services/Yorkshire_Water_Storm_Overflow_Activity/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services-eu1.arcgis.com/OMdMOtfhATJPcHe3/arcgis/rest/services/NEH_outlets_PROD/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services-eu1.arcgis.com/XxS6FebPX29TRGDJ/arcgis/rest/services/Southern_Water_Storm_Overflow_Activity/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services3.arcgis.com/VCOY1atHWVcDlvlJ/arcgis/rest/services/stream_service_outfall_locations_view/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services1.arcgis.com/NO7lTIlnxRMMG9Gw/arcgis/rest/services/Severn_Trent_Water_Storm_Overflow_Activity/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services-eu1.arcgis.com/MSNNjkZ51iVh8yBj/arcgis/rest/services/Northumbrian_Water_Storm_Overflow_Activity_2_view/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json",
    "https://services.arcgis.com/3SZ6e0uCvPROr4mS/arcgis/rest/services/Wessex_Water_Storm_Overflow_Activity/FeatureServer/0/query?where=Status=1&outFields=Id,Company,Latitude,Longitude,ReceivingWaterCourse,LatestEventStart,LastUpdated&f=json"
];